# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b9c7322c6c15ebbe0115dba7a02cee3f81a1c6711991af96e32cbed1968fd49af83c9dd95d75733e8cd4b30d97acbb51733d6eaaae4760d019cfc470f4b7e9a

test:
  secret_key_base: da0dc32054f7f29273fc363a82b960d33cd56b3232fa7a12167bf2c5ee391bb1a17c4c6c5c8f849b7cb2bc830cc3647471097935f1f46dc5cf69a46450330f92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
